artifacts_root: artifacts_root

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack-14.0.json
  local_data_file: artifacts/data_ingestion/data.json
  #unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/data.json
  STATUS_FILE: artifacts/data_validation/status.txt

data_tranformation:
  root_dir: artifacts/data_tranformation
  data_file: artifacts/data_ingestion/data.json
